apiVersion: v1
kind: Service
metadata:
  name: "{{ tpl .Values.scim.name . }}-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ tpl .Values.scim.name . }}
    {{ with .Values.scim.labels }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ with .Values.scim.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.scim.serviceType }}
  selector:
    app: {{ tpl .Values.scim.name . }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.scim.httpPort }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.scim.httpsPort }}
